/**
 * @a83/orbiter-integration
 *
 * Astro integration that:
 * 1. Opens the .pod file at build/dev time
 * 2. Injects virtual module `orbiter:collections` — read published content in Astro pages
 * 3. Injects virtual module `orbiter:db` — pod path for custom server routes
 * 4. Serves media BLOBs at /orbiter/media/[id]
 * 5. Exposes a read-only JSON API at /orbiter/api/[collection]
 *
 * The admin UI runs separately via @a83/orbiter-admin.
 */
import { openPod } from '@a83/orbiter-core';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';
import { writeFileSync } from 'node:fs';

const __dirname = dirname(fileURLToPath(import.meta.url));

function toPascal(str) {
  return str.split(/[-_]/).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join('');
}

function fieldToTs(field, allCols) {
  switch (field.type) {
    case 'string': case 'richtext': case 'url': case 'email':
    case 'date': case 'datetime': case 'image': case 'media':
      return 'string';
    case 'number':   return 'number';
    case 'boolean':  return 'boolean';
    case 'array': case 'weekdays': return 'string[]';
    case 'select':
      return field.options?.length
        ? field.options.map(o => `'${o}'`).join(' | ')
        : 'string';
    case 'relation': {
      const rel = allCols.find(c => c.id === field.collection);
      const t   = rel ? toPascal(rel.id) + 'Entry' : 'OrbiterEntry';
      return field.multiple !== false ? `${t}[]` : `${t} | null`;
    }
    default: return 'unknown';
  }
}

function generateTypes(db) {
  const cols = db.getCollections();
  const out  = [
    '// orbiter-env.d.ts — auto-generated by @a83/orbiter-integration',
    '// Regenerated on each Astro build. Do not edit manually.',
    '',
    "declare module 'orbiter:collections' {",
    '',
    '  export interface OrbiterEntry<T = Record<string, unknown>> {',
    '    id: string;',
    '    slug: string;',
    "    status: 'draft' | 'published';",
    '    created_at: string;',
    '    updated_at: string;',
    '    sort_order: number | null;',
    '    data: T;',
    '  }',
    '',
  ];

  for (const col of cols) {
    const schema = col.schema ? JSON.parse(col.schema) : {};
    const name   = toPascal(col.id);
    out.push(`  // ${col.label}`);
    out.push(`  export interface ${name}Data {`);
    for (const [key, field] of Object.entries(schema)) {
      out.push(`    ${key}?: ${fieldToTs(field, cols)};`);
    }
    out.push('  }');
    out.push(`  export type ${name}Entry = OrbiterEntry<${name}Data>;`);
    out.push('');
  }

  for (const col of cols) {
    out.push(`  export function getCollection(name: '${col.id}'): Promise<${toPascal(col.id)}Entry[]>;`);
  }
  out.push('  export function getCollection(name: string): Promise<OrbiterEntry[]>;');
  out.push('');

  for (const col of cols) {
    out.push(`  export function getEntry(collection: '${col.id}', slug: string): Promise<${toPascal(col.id)}Entry | null>;`);
  }
  out.push('  export function getEntry(collection: string, slug: string): Promise<OrbiterEntry | null>;');
  out.push('');

  out.push('  export function getLocaleCollection(name: string, locale?: string): Promise<OrbiterEntry[]>;');
  out.push('  export function getLocaleEntry(collection: string, baseSlug: string, locale: string): Promise<OrbiterEntry | null>;');
  for (const col of cols) {
    out.push(`  export function getPreviewEntry(collection: '${col.id}', slug: string, previewToken: string): Promise<${toPascal(col.id)}Entry | null>;`);
  }
  out.push('  export function getPreviewEntry(collection: string, slug: string, previewToken: string): Promise<OrbiterEntry | null>;');
  out.push('');
  out.push('  export const locale: string;');
  out.push('  export const locales: string[];');
  out.push('}');
  return out.join('\n') + '\n';
}

const VIRTUAL_COLLECTIONS_ID = 'orbiter:collections';
const RESOLVED_COLLECTIONS_ID = `\0${VIRTUAL_COLLECTIONS_ID}`;

const VIRTUAL_DB_ID = 'orbiter:db';
const RESOLVED_DB_ID = `\0${VIRTUAL_DB_ID}`;

/**
 * Generate the runtime version of orbiter:collections.
 * Schemas are baked at build time (for relation resolution); all content
 * queries hit the pod file at request time — no rebuild needed after edits.
 */
function generateRuntimeModule(podPath, defaultLocale, locales, schemas) {
  return `
import { openPod } from '@a83/orbiter-core';

const _podPath = ${JSON.stringify(podPath)};

export const locale  = ${JSON.stringify(defaultLocale)};
export const locales = ${JSON.stringify(locales)};

// Schemas baked at build time for inline relation resolution
const _schemas = ${JSON.stringify(schemas, null, 2)};

function _resolveRelations(entries, colId, db) {
  const schema = _schemas[colId];
  if (!schema) return entries;
  const relFields = Object.entries(schema).filter(([, f]) => f.type === 'relation');
  if (!relFields.length) return entries;
  const byId = (id) => {
    const row = db.db.prepare(
      'SELECT * FROM _entries WHERE id = ? AND deleted_at IS NULL'
    ).get(id);
    return row ? { ...row, data: JSON.parse(row.data) } : id;
  };
  for (const entry of entries) {
    for (const [key, field] of relFields) {
      const raw  = entry.data[key];
      const ids  = Array.isArray(raw) ? raw : (raw ? [raw] : []);
      const resolved = ids.map(byId).filter(Boolean);
      entry.data[key] = field.multiple !== false ? resolved : (resolved[0] ?? null);
    }
  }
  return entries;
}

export function getCollection(name) {
  const db      = openPod(_podPath);
  const entries = db.getEntries(name, { status: 'published' }).filter(e => (e.locale ?? '') === '');
  _resolveRelations(entries, name, db);
  db.close();
  return Promise.resolve(entries);
}

export function getEntry(collection, slug) {
  const db    = openPod(_podPath);
  const entry = db.getEntry(collection, slug, '');
  if (entry) _resolveRelations([entry], collection, db);
  db.close();
  return Promise.resolve(entry ?? null);
}

export function getLocaleCollection(name, loc) {
  const dbLoc   = (!loc || loc === locales[0]) ? '' : loc;
  const db      = openPod(_podPath);
  const entries = db.getEntries(name, { status: 'published', locale: dbLoc });
  _resolveRelations(entries, name, db);
  db.close();
  return Promise.resolve(entries);
}

export function getLocaleEntry(collection, baseSlug, loc) {
  const dbLoc = (!loc || loc === locales[0]) ? '' : loc;
  const db    = openPod(_podPath);
  let entry   = db.getEntry(collection, baseSlug, dbLoc);
  if (!entry) entry = db.getEntry(collection, baseSlug, '');
  if (entry) _resolveRelations([entry], collection, db);
  db.close();
  return Promise.resolve(entry ?? null);
}

export async function getPreviewEntry(collection, slug, previewToken) {
  const db          = openPod(_podPath);
  const storedToken = db.getMeta('preview.token');
  if (!previewToken || previewToken !== storedToken) { db.close(); return null; }
  const row = db.db
    .prepare('SELECT * FROM _entries WHERE collection_id = ? AND slug = ? AND deleted_at IS NULL')
    .get(collection, slug);
  db.close();
  if (!row) return null;
  return { ...row, data: JSON.parse(row.data) };
}
`;
}

/**
 * @param {{ pod: string }} options
 * @returns {import('astro').AstroIntegration}
 */
export default function orbiter(options = {}) {
  const podPath = options.pod ?? './content.pod';

  return {
    name: '@a83/orbiter-integration',

    hooks: {
      'astro:config:setup': ({ updateConfig, config, injectRoute, logger }) => {
        const mode = (config.output === 'server' || config.output === 'hybrid') ? 'runtime' : 'static';
        logger.info(`◆ Orbiter — loading pod: ${podPath} (${mode} mode)`);

        // Generate TypeScript types from schema
        try {
          const resolvedPod = resolve(config.root.pathname, podPath);
          const db = openPod(resolvedPod);
          const types = generateTypes(db);
          db.close();
          const outPath = resolve(config.root.pathname, 'orbiter-env.d.ts');
          writeFileSync(outPath, types, 'utf8');
          logger.info('◆ Orbiter — wrote orbiter-env.d.ts');
        } catch (e) {
          logger.warn(`◆ Orbiter — could not generate types: ${e.message}`);
        }

        const routesDir = resolve(__dirname, '../routes');

        // Media BLOB serving — public, no auth required
        injectRoute({
          pattern:    '/orbiter/media/[id]',
          entrypoint: resolve(routesDir, 'media-serve.astro'),
        });

        // Read-only JSON API
        injectRoute({
          pattern:    '/orbiter/api/[collection]',
          entrypoint: resolve(routesDir, 'api-collection.js'),
        });

        // RSS feeds per collection
        injectRoute({
          pattern:    '/orbiter/rss/[collection].xml',
          entrypoint: resolve(routesDir, 'rss-feed.js'),
        });

        // XML sitemap for all published entries
        injectRoute({
          pattern:    '/orbiter/sitemap.xml',
          entrypoint: resolve(routesDir, 'sitemap.js'),
        });

        // ── Vite virtual modules ─────────────────
        updateConfig({
          vite: {
            plugins: [
              {
                name: 'orbiter-virtual',
                resolveId(id) {
                  if (id === VIRTUAL_COLLECTIONS_ID) return RESOLVED_COLLECTIONS_ID;
                  if (id === VIRTUAL_DB_ID)          return RESOLVED_DB_ID;
                },
                load(id) {
                  const resolvedPodPath = resolve(
                    config.root.pathname,
                    podPath
                  );

                  // orbiter:collections
                  if (id === RESOLVED_COLLECTIONS_ID) {
                    const db = openPod(resolvedPodPath);
                    const collections   = db.getCollections();
                    const defaultLocale = db.getMeta('site.locale') ?? 'en';
                    const rawLocales    = db.getMeta('site.locales') ?? defaultLocale;
                    const locales       = rawLocales.split(',').map(l => l.trim()).filter(Boolean);

                    // SSR / hybrid: queries hit the pod at request time
                    const isSSR = config.output === 'server' || config.output === 'hybrid';
                    if (isSSR) {
                      const schemas = {};
                      for (const col of collections) {
                        schemas[col.id] = col.schema ? JSON.parse(col.schema) : {};
                      }
                      db.close();
                      return generateRuntimeModule(resolvedPodPath, defaultLocale, locales, schemas);
                    }

                    // Static: snapshot at build time
                    const snapshot = {};
                    for (const col of collections) {
                      snapshot[col.id] = db.getEntries(col.id, { status: 'published' });
                    }

                    // Resolve relation fields inline
                    const byId = {};
                    for (const entries of Object.values(snapshot)) {
                      for (const e of entries) byId[e.id] = e;
                    }
                    for (const col of collections) {
                      const colSchema = col.schema ? JSON.parse(col.schema) : {};
                      const relFields = Object.entries(colSchema).filter(([, f]) => f.type === 'relation');
                      if (!relFields.length) continue;
                      for (const entry of snapshot[col.id] ?? []) {
                        for (const [key, field] of relFields) {
                          const raw = entry.data[key];
                          const ids = Array.isArray(raw) ? raw : (raw ? [raw] : []);
                          const resolved = ids.map(id => byId[id] ?? id).filter(Boolean);
                          entry.data[key] = field.multiple !== false ? resolved : (resolved[0] ?? null);
                        }
                      }
                    }

                    db.close();

                    return `
export const collections = ${JSON.stringify(snapshot, null, 2)};

const _podPath = ${JSON.stringify(resolvedPodPath)};

export const locale  = ${JSON.stringify(defaultLocale)};
export const locales = ${JSON.stringify(locales)};

export function getCollection(name) {
  return Promise.resolve((collections[name] ?? []).filter(e => (e.locale ?? '') === ''));
}

export function getEntry(collection, slug) {
  const entries = collections[collection] ?? [];
  return Promise.resolve(entries.find(e => e.slug === slug && (e.locale ?? '') === '') ?? null);
}

export function getLocaleCollection(name, loc) {
  const all   = collections[name] ?? [];
  const dbLoc = (!loc || loc === locales[0]) ? '' : loc;
  return Promise.resolve(all.filter(e => (e.locale ?? '') === dbLoc));
}

export function getLocaleEntry(collection, baseSlug, loc) {
  const entries = collections[collection] ?? [];
  const dbLoc   = (!loc || loc === locales[0]) ? '' : loc;
  const variant = entries.find(e => e.slug === baseSlug && (e.locale ?? '') === dbLoc);
  if (variant) return Promise.resolve(variant);
  return Promise.resolve(entries.find(e => e.slug === baseSlug && (e.locale ?? '') === '') ?? null);
}

export async function getPreviewEntry(collection, slug, previewToken) {
  const { openPod } = await import('@a83/orbiter-core');
  const db = openPod(_podPath);
  const storedToken = db.getMeta('preview.token');
  if (!previewToken || previewToken !== storedToken) { db.close(); return null; }
  const row = db.db.prepare(
    'SELECT * FROM _entries WHERE collection_id = ? AND slug = ? AND deleted_at IS NULL'
  ).get(collection, slug);
  db.close();
  if (!row) return null;
  return { ...row, data: JSON.parse(row.data) };
}
`;
                  }

                  // orbiter:db — pod path for custom server routes
                  if (id === RESOLVED_DB_ID) {
                    return `export const podPath = ${JSON.stringify(resolvedPodPath)};`;
                  }
                },
              },
            ],
          },
        });
      },
    },
  };
}
